version: "3.4"

services:
  godocker:
    image: godocker
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: ["db"]
    ports:
      - 5555:5555

  db:
    image: mariadb:10-focal
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker_test
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
